// <auto-generated />
using System;
using BeSpokedBikesWeb.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeSpokedBikesWeb.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220417200359_appContextToDB")]
    partial class appContextToDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BeSpokedBikesWeb.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4697 Robinson Lane Worthington, OH 43085",
                            FirstName = "Jeffery",
                            LastName = "Petties",
                            Phone = "740-337-9500",
                            StartDate = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "2345 Beech Street Concord, CA 94520",
                            FirstName = "Barbara",
                            LastName = "Weiss",
                            Phone = "925-825-6717",
                            StartDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "2436 Kessla Way Hardeeville, SC 29927",
                            FirstName = "Thomas",
                            LastName = "Kearney",
                            Phone = "843-288-0173",
                            StartDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BeSpokedBikesWeb.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginDate = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 10,
                            EndDate = new DateTime(2020, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Aventon 2022 Soltera 7 Speed Electric Road Bike"
                        },
                        new
                        {
                            Id = 2,
                            BeginDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 5,
                            EndDate = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Specialized 2021 Turbo Creo SL E5 Comp Electric Road Bike"
                        },
                        new
                        {
                            Id = 3,
                            BeginDate = new DateTime(2022, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 20,
                            EndDate = new DateTime(2021, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Product = "Cervelo 2022 Aspero Apex 1 Gravel Road Bike"
                        });
                });

            modelBuilder.Entity("BeSpokedBikesWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommissionPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionPercentage = 1,
                            Manufacturer = "Aventon",
                            Name = "Aventon 2022 Soltera 7 Speed Electric Road Bike",
                            PurchasePrice = 2499.99m,
                            QtyOnHand = 10,
                            SalePrice = 2799.99m,
                            Style = "Sport"
                        },
                        new
                        {
                            Id = 2,
                            CommissionPercentage = 2,
                            Manufacturer = "Specialized",
                            Name = "Specialized 2021 Turbo Creo SL E5 Comp Electric Road Bike",
                            PurchasePrice = 1499.99m,
                            QtyOnHand = 16,
                            SalePrice = 1799.99m,
                            Style = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            CommissionPercentage = 3,
                            Manufacturer = "Cervelo",
                            Name = "Cervelo 2022 Aspero Apex 1 Gravel Road Bike",
                            PurchasePrice = 499.99m,
                            QtyOnHand = 4,
                            SalePrice = 799.99m,
                            Style = "Sport"
                        });
                });

            modelBuilder.Entity("BeSpokedBikesWeb.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SalesDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salesperson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Customer = "Jeffery Petties",
                            Product = "Cervelo 2022 Aspero Apex 1 Gravel Road Bike",
                            SalesDate = new DateTime(2021, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salesperson = "Amanda Barber"
                        });
                });

            modelBuilder.Entity("BeSpokedBikesWeb.Models.Salesperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Salespersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "3029 Duck Creek Road Palo Alto, CA 94306",
                            FirstName = "Amanda",
                            LastName = "Barber",
                            Manager = "",
                            Phone = "650-846-2128",
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "683 Medical Center Drive Venice, FL 34285",
                            FirstName = "Jim",
                            LastName = "Mayfield",
                            Manager = "Amanda Barber",
                            Phone = "941-496-1012",
                            StartDate = new DateTime(2021, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "2450 Poco Mas Drive Dallas, TX 75247",
                            FirstName = "James",
                            LastName = "Lawson",
                            Manager = "Amanda Barber",
                            Phone = "214-454-1619",
                            StartDate = new DateTime(2021, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TerminationDate = new DateTime(2022, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
